# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="FFI binding to the CUDA interface for programming NVIDIA GPUs"
HOMEPAGE="https://github.com/tmcdonell/cuda"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/uuid-types-1.0:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	>=dev-util/nvidia-cuda-toolkit-11:=[profiler] <dev-util/nvidia-cuda-toolkit-12:=[profiler]
"
DEPEND="${RDEPEND}
	dev-haskell/c2hs
	>=dev-haskell/cabal-3.4.1.0 <dev-haskell/cabal-3.11
"
